import sys
import importlib

_MODULE_MAP = {
    'ai_quantizer': 'actool_linux.codecs.ai_quantizer',
    'alpha_compression': 'actool_linux.codecs.alpha_compression',
    'appicons': 'actool_linux.assets.appicons',
    'astc_compression': 'actool_linux.codecs.astc_compression',
    'astc_optimized': 'actool_linux.codecs.astc_optimized',
    'astc_optimizer': 'actool_linux.codecs.astc_optimizer',
    'atlas': 'actool_linux.assets.atlas',
    'atlas_geometry': 'actool_linux.assets.atlas_geometry',
    'bom': 'actool_linux.core.bom',
    'bomwriter': 'actool_linux.core.bomwriter',
    'capabilities': 'actool_linux.tools.capabilities',
    'car': 'actool_linux.core.car',
    'carinfo': 'actool_linux.core.carinfo',
    'carwriter': 'actool_linux.core.carwriter',
    'cbck': 'actool_linux.codecs.cbck',
    'cbck_complete': 'actool_linux.codecs.cbck_complete',
    'cli': 'actool_linux.tools.cli',
    'compiler': 'actool_linux.tools.compiler',
    'coreui': 'actool_linux.core.coreui',
    'csi': 'actool_linux.core.csi',
    'diagnostics': 'actool_linux.tools.diagnostics',
    'dmp2mini': 'actool_linux.codecs.dmp2mini',
    'facet_hash_lookup': 'actool_linux.core.facet_hash_lookup',
    'hybrid_compression': 'actool_linux.codecs.hybrid_compression',
    'iconstack': 'actool_linux.assets.iconstack',
    'imagestack': 'actool_linux.assets.imagestack',
    'legacy_coreui_features': 'actool_linux.tools.legacy_coreui_features',
    'lpc_lzfse': 'actool_linux.codecs.lpc_lzfse',
    'lzfse_compat': 'actool_linux.codecs.lzfse_compat',
    'lzfse_optimized': 'actool_linux.codecs.lzfse_optimized',
    'model': 'actool_linux.tools.model',
    'multi_database': 'actool_linux.core.multi_database',
    'nexus_compression': 'actool_linux.codecs.nexus_compression',
    'omega_compression': 'actool_linux.codecs.omega_compression',
    'omega_plus': 'actool_linux.codecs.omega_plus',
    'omni_compression': 'actool_linux.codecs.omni_compression',
    'omniv2_compression': 'actool_linux.codecs.omniv2_compression',
    'packed': 'actool_linux.assets.packed',
    'paletteimg': 'actool_linux.codecs.paletteimg',
    'pdfcar': 'actool_linux.assets.pdfcar',
    'planar_delta_lzfse': 'actool_linux.codecs.planar_delta_lzfse',
    'quality_metrics': 'actool_linux.safety.quality_metrics',
    'repack': 'actool_linux.tools.repack',
    'semantic_fusion': 'actool_linux.codecs.semantic_fusion',
    'smart_cbck': 'actool_linux.codecs.smart_cbck',
    'solidstack': 'actool_linux.assets.solidstack',
    'tet_complete': 'actool_linux.codecs.tet_complete',
    'tet_compression': 'actool_linux.codecs.tet_compression',
    'tet_full': 'actool_linux.codecs.tet_full',
    'tet_ultimate': 'actool_linux.codecs.tet_ultimate',
    'tet_variants': 'actool_linux.codecs.tet_variants',
    'texture': 'actool_linux.assets.texture',
    'texture_gradient_stack': 'actool_linux.assets.texture_gradient_stack',
    'thinning': 'actool_linux.assets.thinning',
    'tree': 'actool_linux.core.tree',
    'ultimate_compression': 'actool_linux.codecs.ultimate_compression',
    'zero_code_db': 'actool_linux.core.zero_code_db',
}

def __getattr__(name: str):
    if name in _MODULE_MAP:
        mod = importlib.import_module(_MODULE_MAP[name])
        sys.modules[f"{__name__}.{name}"] = mod
        return mod
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
