[book]
authors = ["kagurasumusun"]
language = "ja"
multilingual = false
src = "src"
title = "Apple Toolsets Technical Book & Specification"

[build]
build-dir = "book_html"
create-missing = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/kagurasumusun/Apple-Toolsets"
git-repository-icon = "fa-github"
mathjax-support = true
