"""
classes_db.py - Apple ibtool の --classes 出力に含まれる全 built-in class データ

Apple ibtool の --classes 出力には Apple の内部 class DB (UIKit 全クラス等) が含まれる。
これは公開 xib には通常存在しないが、ibtool の出力には常に入る。
本実装でも、xib 内 class と組み合わせて完全 DB を出力する。
"""

# Apple ibtool 出力から抽出した built-in UIKit / Foundation class DB
# (Xcode 26.5 / iOS 26 SDK)
# key: クラス名, value: { class, superclass?, actions?, outlets?, multi-outlets? }
APPLE_CLASSES_DB = {
    "ADBannerView": {"class": "ADBannerView", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "ARSCNView": {"class": "ARSCNView", "superclass": "SCNView"},
    "ARSKView": {"class": "ARSKView", "superclass": "SKView"},
    "ARView": {"class": "ARView", "superclass": "UIView"},
    "AVPlayerViewController": {"class": "AVPlayerViewController", "outlets": {"delegate": "id"}, "superclass": "UIViewController"},
    "FirstResponder": {"class": "FirstResponder"},
    "GLKView": {"class": "GLKView", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "GLKViewController": {"class": "GLKViewController", "outlets": {"delegate": "id"}, "superclass": "UIViewController"},
    "MKMapView": {"class": "MKMapView", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "NSArray": {"class": "NSArray", "superclass": "NSObject"},
    "NSAtomicStore": {"class": "NSAtomicStore", "superclass": "NSPersistentStore"},
    "NSAtomicStoreCacheNode": {"class": "NSAtomicStoreCacheNode", "superclass": "NSObject"},
    "NSAttributeDescription": {"class": "NSAttributeDescription", "superclass": "NSPropertyDescription"},
    "NSAttributedString": {"class": "NSAttributedString", "superclass": "NSObject"},
    "NSAutoreleasePool": {"class": "NSAutoreleasePool", "superclass": "NSObject"},
    "NSBundle": {"class": "NSBundle", "superclass": "NSObject"},
    "NSByteCountFormatter": {"class": "NSByteCountFormatter", "superclass": "NSFormatter"},
    "NSCache": {"class": "NSCache", "superclass": "NSObject"},
    "NSCachedURLResponse": {"class": "NSCachedURLResponse", "superclass": "NSObject"},
    "NSCalendar": {"class": "NSCalendar", "superclass": "NSObject"},
    "NSCoder": {"class": "NSCoder"},  # Apple 出力では superclass キー無し
    "NSComparisonPredicate": {"class": "NSComparisonPredicate", "superclass": "NSPredicate"},
    "NSCompoundPredicate": {"class": "NSCompoundPredicate", "superclass": "NSPredicate"},
    "NSData": {"class": "NSData", "superclass": "NSObject"},
    "NSDateFormatter": {"class": "NSDateFormatter", "superclass": "NSFormatter"},
    "NSDecimalNumber": {"class": "NSDecimalNumber", "superclass": "NSNumber"},
    "NSEntityDescription": {"class": "NSEntityDescription", "superclass": "NSObject"},
    "NSEntityMapping": {"class": "NSEntityMapping", "superclass": "NSObject"},
    "NSEntityMigrationPolicy": {"class": "NSEntityMigrationPolicy", "superclass": "NSObject"},
    "NSError": {"class": "NSError", "superclass": "NSObject"},
    "NSException": {"class": "NSException", "superclass": "NSObject"},
    "NSExpression": {"class": "NSExpression", "superclass": "NSObject"},
    "NSExpressionDescription": {"class": "NSExpressionDescription", "superclass": "NSPropertyDescription"},
    "NSFetchRequest": {"class": "NSFetchRequest", "superclass": "NSObject"},
    "NSFetchRequestExpression": {"class": "NSFetchRequestExpression", "superclass": "NSExpression"},
    "NSFetchedPropertyDescription": {"class": "NSFetchedPropertyDescription", "superclass": "NSPropertyDescription"},
    "NSFetchedResultsController": {"class": "NSFetchedResultsController", "superclass": "NSObject"},
    "NSFileWrapper": {"class": "NSFileWrapper", "superclass": "NSObject"},
    "NSFormatter": {"class": "NSFormatter"},
    "NSHTTPCookie": {"class": "NSHTTPCookie", "superclass": "NSObject"},
    "NSHTTPCookieStorage": {"class": "NSHTTPCookieStorage", "superclass": "NSObject"},
    "NSIndexPath": {"class": "NSIndexPath", "superclass": "NSObject"},
    "NSIndexSet": {"class": "NSIndexSet", "superclass": "NSObject"},
    "NSInvocation": {"class": "NSInvocation", "superclass": "NSObject"},
    "NSKeyedArchiver": {"class": "NSKeyedArchiver", "superclass": "NSCoder"},
    "NSLocale": {"class": "NSLocale", "superclass": "NSObject"},
    "NSLock": {"class": "NSLock", "superclass": "NSObject"},
    "NSManagedObject": {"class": "NSManagedObject", "superclass": "NSObject"},
    "NSManagedObjectContext": {"class": "NSManagedObjectContext", "superclass": "NSObject"},
    "NSManagedObjectID": {"class": "NSManagedObjectID", "superclass": "NSObject"},
    "NSManagedObjectModel": {"class": "NSManagedObjectModel", "superclass": "NSObject"},
    "NSMappingModel": {"class": "NSMappingModel", "superclass": "NSObject"},
    "NSMethodSignature": {"class": "NSMethodSignature", "superclass": "NSObject"},
    "NSMigrationManager": {"class": "NSMigrationManager", "superclass": "NSObject"},
    "NSNetService": {"class": "NSNetService", "superclass": "NSObject"},
    "NSNotification": {"class": "NSNotification", "superclass": "NSObject"},
    "NSNotificationQueue": {"class": "NSNotificationQueue", "superclass": "NSObject"},
    "NSNumber": {"class": "NSNumber"},
    "NSNumberFormatter": {"class": "NSNumberFormatter", "superclass": "NSFormatter"},
    "NSObject": {"class": "NSObject"},
    "NSOperation": {"class": "NSOperation", "superclass": "NSObject"},
    "NSPersistentStore": {"class": "NSPersistentStore", "superclass": "NSObject"},
    "NSPersistentStoreCoordinator": {"class": "NSPersistentStoreCoordinator", "superclass": "NSObject"},
    "NSPort": {"class": "NSPort", "superclass": "NSObject"},
    "NSPredicate": {"class": "NSPredicate", "superclass": "NSObject"},
    "NSProcessInfo": {"class": "NSProcessInfo", "superclass": "NSObject"},
    "NSPropertyDescription": {"class": "NSPropertyDescription", "superclass": "NSObject"},
    "NSPropertyListSerialization": {"class": "NSPropertyListSerialization", "superclass": "NSObject"},
    "NSPropertyMapping": {"class": "NSPropertyMapping", "superclass": "NSObject"},
    "NSRegularExpression": {"class": "NSRegularExpression", "superclass": "NSObject"},
    "NSRelationshipDescription": {"class": "NSRelationshipDescription", "superclass": "NSPropertyDescription"},
    "NSRunLoop": {"class": "NSRunLoop", "superclass": "NSObject"},
    "NSSet": {"class": "NSSet", "superclass": "NSObject"},
    "NSSortDescriptor": {"class": "NSSortDescriptor", "superclass": "NSObject"},
    "NSString": {"class": "NSString", "superclass": "NSObject"},
    "NSThread": {"class": "NSThread", "superclass": "NSObject"},
    "NSTimeZone": {"class": "NSTimeZone", "superclass": "NSObject"},
    "NSURL": {"class": "NSURL", "superclass": "NSObject"},
    "NSURLAuthenticationChallenge": {"class": "NSURLAuthenticationChallenge", "superclass": "NSObject"},
    "NSURLConnection": {"class": "NSURLConnection", "superclass": "NSObject"},
    "NSURLCredential": {"class": "NSURLCredential", "superclass": "NSObject"},
    "NSURLCredentialStorage": {"class": "NSURLCredentialStorage", "superclass": "NSObject"},
    "NSURLProtectionSpace": {"class": "NSURLProtectionSpace", "superclass": "NSObject"},
    "NSURLProtocol": {"class": "NSURLProtocol", "superclass": "NSObject"},
    "NSURLRequest": {"class": "NSURLRequest", "superclass": "NSObject"},
    "NSURLResponse": {"class": "NSURLResponse", "superclass": "NSObject"},
    "NSUndoManager": {"class": "NSUndoManager", "actions": {"redo:": "id", "undo:": "id"}, "superclass": "NSObject"},
    "NSUserDefaults": {"class": "NSUserDefaults", "superclass": "NSObject"},
    "NSValueTransformer": {"class": "NSValueTransformer", "superclass": "NSObject"},
    "NSXMLParser": {"class": "NSXMLParser", "superclass": "NSObject"},
    "QLPreviewController": {"class": "QLPreviewController", "outlets": {"dataSource": "id", "delegate": "id"}, "superclass": "UIViewController"},
    "RoomCaptureView": {"class": "RoomCaptureView", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "SCNView": {"class": "SCNView", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "SFSafariViewController": {"class": "SFSafariViewController", "outlets": {"delegate": "id"}, "superclass": "UIViewController"},
    "SKView": {"class": "SKView", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "UIAcceleration": {"class": "UIAcceleration", "superclass": "NSObject"},
    "UIAccelerometer": {"class": "UIAccelerometer", "superclass": "NSObject"},
    "UIAccessibilityElement": {"class": "UIAccessibilityElement", "superclass": "NSObject"},
    "UIActionSheet": {"class": "UIActionSheet", "superclass": "UIView"},
    "UIActivityIndicatorView": {"class": "UIActivityIndicatorView", "superclass": "UIView"},
    "UIAlertView": {"class": "UIAlertView", "superclass": "UIView"},
    "UIApplication": {"class": "UIApplication", "outlets": {"delegate": "id"}, "superclass": "UIResponder"},
    "UIBarButtonItem": {"class": "UIBarButtonItem", "superclass": "UIBarItem"},
    "UIBarItem": {"class": "UIBarItem", "superclass": "NSObject"},
    "UIBezierPath": {"class": "UIBezierPath", "superclass": "NSObject"},
    "UIButton": {"class": "UIButton", "superclass": "UIControl"},
    "UICollectionReusableView": {"class": "UICollectionReusableView", "superclass": "UIView"},
    "UICollectionView": {"class": "UICollectionView", "outlets": {"dataSource": "id", "dragDelegate": "id", "dropDelegate": "id", "prefetchDataSource": "id"}, "superclass": "UIScrollView"},
    "UICollectionViewCell": {"class": "UICollectionViewCell", "outlets": {"backgroundView": "UIView", "selectedBackgroundView": "UIView"}, "superclass": "UICollectionReusableView"},
    "UICollectionViewController": {"class": "UICollectionViewController", "outlets": {"collectionView": "UICollectionView"}, "superclass": "UIViewController"},
    "UIColor": {"class": "UIColor", "superclass": "NSObject"},
    "UIControl": {"class": "UIControl", "superclass": "UIView"},
    "UIDatePicker": {"class": "UIDatePicker", "superclass": "UIControl"},
    "UIDevice": {"class": "UIDevice", "superclass": "NSObject"},
    "UIDocumentInteractionController": {"class": "UIDocumentInteractionController", "superclass": "NSObject"},
    "UIEvent": {"class": "UIEvent", "superclass": "NSObject"},
    "UIFont": {"class": "UIFont", "superclass": "NSObject"},
    "UIGestureRecognizer": {"class": "UIGestureRecognizer", "outlets": {"delegate": "id"}, "superclass": "NSObject"},
    "UIImage": {"class": "UIImage", "superclass": "NSObject"},
    "UIImagePickerController": {"class": "UIImagePickerController", "superclass": "UINavigationController"},
    "UIImageView": {"class": "UIImageView", "superclass": "UIView"},
    "UIInputView": {"class": "UIInputView", "superclass": "UIView"},
    "UIInputViewController": {"class": "UIInputViewController", "outlets": {"inputView": "UIInputView"}, "superclass": "UIViewController"},
    "UILabel": {"class": "UILabel", "superclass": "UIView"},
    "UILayoutGuide": {"class": "UILayoutGuide"},
    "UILocalizedIndexedCollation": {"class": "UILocalizedIndexedCollation", "superclass": "NSObject"},
    "UILongPressGestureRecognizer": {"class": "UILongPressGestureRecognizer", "superclass": "UIGestureRecognizer"},
    "UIMenuController": {"class": "UIMenuController", "superclass": "NSObject"},
    "UINavigationBar": {"class": "UINavigationBar", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "UINavigationController": {"class": "UINavigationController", "outlets": {"delegate": "id"}, "superclass": "UIViewController"},
    "UINavigationItem": {"class": "UINavigationItem", "outlets": {"backBarButtonItem": "UIBarButtonItem", "leftBarButtonItem": "UIBarButtonItem", "rightBarButtonItem": "UIBarButtonItem", "titleView": "UIView"}, "superclass": "NSObject"},
    "UINib": {"class": "UINib", "superclass": "NSObject"},
    "UIPageControl": {"class": "UIPageControl", "superclass": "UIControl"},
    "UIPageViewController": {"class": "UIPageViewController", "outlets": {"dataSource": "id", "delegate": "id"}, "superclass": "UIViewController"},
    "UIPanGestureRecognizer": {"class": "UIPanGestureRecognizer", "superclass": "UIGestureRecognizer"},
    "UIPasteboard": {"class": "UIPasteboard", "superclass": "NSObject"},
    "UIPickerView": {"class": "UIPickerView", "outlets": {"dataSource": "id", "delegate": "id"}, "superclass": "UIView"},
    "UIPinchGestureRecognizer": {"class": "UIPinchGestureRecognizer", "superclass": "UIGestureRecognizer"},
    "UIPopoverController": {"class": "UIPopoverController", "superclass": "NSObject"},
    "UIProgressView": {"class": "UIProgressView", "superclass": "UIView"},
    "UIRefreshControl": {"class": "UIRefreshControl", "superclass": "UIControl"},
    "UIResponder": {"class": "UIResponder", "superclass": "NSObject"},
    "UIRotationGestureRecognizer": {"class": "UIRotationGestureRecognizer", "superclass": "UIGestureRecognizer"},
    "UIScreen": {"class": "UIScreen", "superclass": "NSObject"},
    "UIScreenEdgePanGestureRecognizer": {"class": "UIScreenEdgePanGestureRecognizer", "superclass": "UIPanGestureRecognizer"},
    "UIScreenMode": {"class": "UIScreenMode", "superclass": "NSObject"},
    "UIScrollView": {"class": "UIScrollView", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "UISearchBar": {"class": "UISearchBar", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "UISearchDisplayController": {"class": "UISearchDisplayController", "outlets": {"delegate": "id", "searchBar": "UISearchBar", "searchContentsController": "UIViewController", "searchResultsDataSource": "id", "searchResultsDelegate": "id"}, "superclass": "NSObject"},
    "UISegmentedControl": {"class": "UISegmentedControl", "superclass": "UIControl"},
    "UISlider": {"class": "UISlider", "superclass": "UIControl"},
    "UISplitViewController": {"class": "UISplitViewController", "outlets": {"delegate": "id"}, "superclass": "UIViewController"},
    "UIStackView": {"class": "UIStackView", "superclass": "UIView"},
    "UIStepper": {"class": "UIStepper", "superclass": "UIControl"},
    "UISwipeGestureRecognizer": {"class": "UISwipeGestureRecognizer", "superclass": "UIGestureRecognizer"},
    "UISwitch": {"class": "UISwitch", "superclass": "UIControl"},
    "UITabBar": {"class": "UITabBar", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "UITabBarController": {"class": "UITabBarController", "outlets": {"delegate": "id"}, "superclass": "UIViewController"},
    "UITabBarItem": {"class": "UITabBarItem", "superclass": "UIBarItem"},
    "UITableView": {"class": "UITableView", "outlets": {"dataSource": "id", "prefetchDataSource": "id"}, "superclass": "UIScrollView"},
    "UITableViewCell": {"class": "UITableViewCell", "outlets": {"accessoryView": "UIView", "backgroundView": "UIView", "editingAccessoryView": "UIView", "selectedBackgroundView": "UIView"}, "superclass": "UIView"},
    "UITableViewCellContentView": {"class": "UITableViewCellContentView", "superclass": "UIView"},
    "UITableViewController": {"class": "UITableViewController", "superclass": "UIViewController"},
    "UITapGestureRecognizer": {"class": "UITapGestureRecognizer", "superclass": "UIGestureRecognizer"},
    "UITextChecker": {"class": "UITextChecker", "superclass": "NSObject"},
    "UITextField": {"class": "UITextField", "actions": {"toggleBoldface:": "id", "toggleItalics:": "id", "toggleUnderline:": "id"}, "outlets": {"delegate": "id", "pasteDelegate": "id", "textDragDelegate": "id", "textDropDelegate": "id"}, "superclass": "UIControl"},
    "UITextPosition": {"class": "UITextPosition", "superclass": "NSObject"},
    "UITextView": {"class": "UITextView", "actions": {"copy:": "id", "cut:": "id", "paste:": "id", "select:": "id", "selectAll:": "id", "toggleBoldface:": "id", "toggleItalics:": "id", "toggleUnderline:": "id"}, "outlets": {"pasteDelegate": "id", "textDragDelegate": "id", "textDropDelegate": "id"}, "superclass": "UIScrollView"},
    "UIToolbar": {"class": "UIToolbar", "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "UITouch": {"class": "UITouch", "superclass": "NSObject"},
    "UIVideoEditorController": {"class": "UIVideoEditorController", "superclass": "UINavigationController"},
    "UIView": {"class": "UIView", "multi-outlets": {"gestureRecognizers": "UIGestureRecognizer"}, "superclass": "UIResponder"},
    "UIViewController": {"class": "UIViewController", "outlets": {"searchDisplayController": "UISearchDisplayController", "view": "UIView"}, "superclass": "UIResponder"},
    "UIVisualEffectView": {"class": "UIVisualEffectView", "superclass": "UIView"},
    "UIWebView": {"class": "UIWebView", "actions": {"goBack": "id", "goForward": "id", "reload": "id", "stopLoading": "id"}, "outlets": {"delegate": "id"}, "superclass": "UIView"},
    "UIWindow": {"class": "UIWindow", "outlets": {"rootViewController": "UIViewController"}, "superclass": "UIView"},
}
